cBcaelL = {}
local gl = GetLocale()

if gl == "deDE" then
   cBcaelL.Armor = "Rüstung"
   cBcaelL.Weapon = "Waffe"
   cBcaelL.Gem = "Juwelen"
   cBcaelL.Trades = "Handwerkswaren"
   cBcaelL.Consumables = "Verbrauchbar"
   cBcaelL.Quest = "Quest"
   cBcaelL.SoulShard = "Seelensplitter"
   cBcaelL.Arrow = "Pfeil"
   cBcaelL.Bullet = "Patrone"
   cBcaelL.bagCaptions = {
        ["cBcael_Bank"] 			= "Bank",
        ["cBcael_BankArmor"]		= "Waffen & Rüstung",
        ["cBcael_BankQuest"]		= "Quest Items",
        ["cBcael_BankTrade"]		= "Handwerkswaren",
        ["cBcael_BankCons"]		= "Verbrauchbar",
		["cBcael_Soulshards"] 	= "Seelensplitter",
        ["cBcael_Ammo"]      	= "Munition",
		["cBcael_Stuff"]			= "Cooles Zeugs",
		["cBcael_ItemSets"]	    = "Sets",
		["cBcael_Armor"]			= "Waffen & Rüstung",
        ["cBcael_Quest"]			= "Quest Items",
		["cBcael_Consumables"]	= "Verbrauchbar",
        ["cBcael_TradeGoods"]	= "Handwerkswaren",
		["cBcael_Bag"]			= "Inventar",
		["cBcael_Keyring"]		= "Schlüsselring",
		["cBcael_NewItems"]		= "Neue Items",
    }
elseif gl == "zhTW" then
    cBcaelL.Armor = "護甲"
    cBcaelL.Weapon = "武器"
    cBcaelL.Gem = "珠寶"
    cBcaelL.Trades = "商品"
    cBcaelL.Consumables = "消耗品"
    cBcaelL.Quest = "任務"
    cBcaelL.SoulShard = "靈魂裂片"
    cBcaelL.Arrow = "箭"
    cBcaelL.Bullet = "子彈"
    cBcaelL.bagCaptions = {
        ["cBcael_Bank"]          = "銀行",
        ["cBcael_BankArmor"]		= "裝備",
        ["cBcael_BankQuest"]		= "任務物品",
        ["cBcael_BankTrade"]		= "商品",
        ["cBcael_BankCons"]		= "消耗品",
        ["cBcael_Soulshards"]    = "靈魂裂片",
        ["cBcael_Ammo"]          = "彈藥",
        ["cBcael_Stuff"]         = "施法材料",
        ["cBcael_ItemSets"]      = "套裝",
        ["cBcael_Armor"]         = "裝備",
        ["cBcael_Quest"]         = "任務物品",
        ["cBcael_Consumables"]   = "消耗品",
        ["cBcael_TradeGoods"]    = "商品",
        ["cBcael_Bag"]           = "存貨",
        ["cBcael_Keyring"]       = "鑰匙扣",
        ["cBcael_NewItems"]      = "新增",
    }
elseif gl == "zhCN" then
    cBcaelL.Armor = "护甲"
    cBcaelL.Weapon = "武器"
    cBcaelL.Gem = "珠宝"
    cBcaelL.Trades = "商品"
    cBcaelL.Consumables = "消耗品"
    cBcaelL.Quest = "任务"
    cBcaelL.SoulShard = "灵魂碎片"
    cBcaelL.Arrow = "箭"
    cBcaelL.Bullet = "子弹"
    cBcaelL.bagCaptions = {
        ["cBcael_Bank"]          = "银行",
        ["cBcael_BankArmor"]		= "装备",
        ["cBcael_BankQuest"]		= "任务物品",
        ["cBcael_BankTrade"]		= "商品",
        ["cBcael_BankCons"]		= "消耗品",
        ["cBcael_Soulshards"]    = "灵魂碎片",
        ["cBcael_Ammo"]          = "弹药",
        ["cBcael_Stuff"]         = "施法材料",
        ["cBcael_ItemSets"]      = "套装",
        ["cBcael_Armor"]         = "装备",
        ["cBcael_Quest"]         = "任务物品",
        ["cBcael_Consumables"]   = "消耗品",
        ["cBcael_TradeGoods"]    = "商品",
        ["cBcael_Bag"]           = "存货",
        ["cBcael_Keyring"]       = "钥匙扣",
        ["cBcael_NewItems"]      = "新增",
    }
elseif gl == "koKR" then
   cBcaelL.Armor = "방어구"
   cBcaelL.Weapon = "무기"
   cBcaelL.Gem = "보석"
   cBcaelL.Trades = "직업용품"
   cBcaelL.Consumables = "소비용품"
   cBcaelL.Quest = "퀘스트"
   cBcaelL.SoulShard = "영혼의 조각"
   cBcaelL.Arrow = "화살"
   cBcaelL.Bullet = "탄약"
   cBcaelL.bagCaptions = {
        ["cBcael_Bank"]  		= "은행",
        ["cBcael_BankArmor"]		= "무기 & 방어구",
        ["cBcael_BankQuest"]		= "퀘스트",
        ["cBcael_BankTrade"]		= "직업용품",
        ["cBcael_BankCons"]		= "소비용품",
		["cBcael_Soulshards"] 	= "영혼의 조각",
        ["cBcael_Ammo"]      	= "화살/탄약",
		["cBcael_Stuff"]	    	= "지정",
		["cBcael_ItemSets"]	    = "세트",
		["cBcael_Armor"]		    = "무기 & 방어구",
		["cBcael_Quest"]		    = "퀘스트",
		["cBcael_Consumables"]	= "소비용품",
        ["cBcael_TradeGoods"]	= "직업용품",
		["cBcael_Bag"]		    = "가방",
		["cBcael_Keyring"]	    = "열쇠고리",
		["cBcael_NewItems"]	    = "신규",
    }    
elseif gl == "ruRU" then
    cBcaelL.Armor = "Доспехи"
    cBcaelL.Weapon = "Оружие"
    cBcaelL.Gem = "Самоцветы"
    cBcaelL.Trades = "Хозяйственные товары"
    cBcaelL.Consumables = "Расходуемые"
    cBcaelL.Quest = "Задания"
    cBcaelL.SoulShard = "Осколок души"
    cBcaelL.Arrow = "Стрелы"
    cBcaelL.Bullet = "Патроны"
    cBcaelL.bagCaptions = {
		["cBcael_Bank"] 			= "Bank",
        ["cBcael_BankArmor"]		= "Weapons & Armor",
        ["cBcael_BankQuest"]		= "Quest Items",
        ["cBcael_BankTrade"]		= "Trade Goods",
        ["cBcael_BankCons"]		= "Consumables",
		["cBcael_Soulshards"] 	= "Soul Shards",
        ["cBcael_Ammo"]      	= "Ammo",
		["cBcael_Stuff"]			= "Cool Stuff",
		["cBcael_ItemSets"]	    = "Sets",
		["cBcael_Armor"]			= "Weapons & Armor",
		["cBcael_Quest"]			= "Quest Items",
		["cBcael_Consumables"]	= "Consumables",
        ["cBcael_TradeGoods"]    = "Trade Goods",
		["cBcael_Bag"]			= "Inventory",
		["cBcael_Keyring"]		= "Keyring",
		["cBcael_NewItems"]		= "New Items",
    }
elseif gl == "frFR" then
    cBcaelL.Armor = "Armure"
    cBcaelL.Weapon = "Arme"
    cBcaelL.Gem = "Gemme"
    cBcaelL.Trades = "Artisanat"
    cBcaelL.Consumables = "Consommable"
    cBcaelL.Quest = "Qu\195\170te"
    cBcaelL.SoulShard = "Fragment d'\195\162me"
    cBcaelL.Arrow = "Fl\195\168che"
    cBcaelL.Bullet = "Balle"
    cBcaelL.bagCaptions = {
		["cBcael_Bank"] 			= "Banque",
        ["cBcael_BankArmor"]		= "Armes et Armures",
        ["cBcael_BankQuest"]		= "Qu\195\170te",
        ["cBcael_BankTrade"]		= "Trade Goods",
        ["cBcael_BankCons"]		= "Concommables",
		["cBcael_Soulshards"] 	= "Fragment d'\195\162me",
		["cBcael_Ammo"]      	= "Munitions",
		["cBcael_Stuff"]			= "Divers",
		["cBcael_ItemSets"]	    = "Sets",
		["cBcael_Armor"]			= "Armes et Armures",
		["cBcael_Quest"]			= "Qu\195\170te",
		["cBcael_Consumables"]	= "Concommables",
        ["cBcael_TradeGoods"]    = "Trade Goods",
		["cBcael_Bag"]			= "Inventaire",
		["cBcael_Keyring"]		= "Porte-Clef",
		["cBcael_NewItems"]		= "Nouveaux Items",
    }   
else
    cBcaelL.Armor = "Armor"
    cBcaelL.Weapon = "Weapon"
    cBcaelL.Gem = "Gem"
    cBcaelL.Trades = "Trade Goods"
    cBcaelL.Consumables = "Consumable"
    cBcaelL.Quest = "Quest"
    cBcaelL.SoulShard = "Soul Shard"
    cBcaelL.Arrow = "Arrow"
    cBcaelL.Bullet = "Bullet"
    cBcaelL.bagCaptions = {
        ["cBcael_Bank"] 			= "Bank",
        ["cBcael_BankArmor"]		= "Weapons & Armor",
        ["cBcael_BankQuest"]		= "Quest Items",
        ["cBcael_BankTrade"]		= "Trade Goods",
        ["cBcael_BankCons"]		= "Consumables",
		["cBcael_Soulshards"] 	= "Soul Shards",
        ["cBcael_Ammo"]      	= "Ammo",
		["cBcael_Stuff"]			= "Cool Stuff",
		["cBcael_ItemSets"]	    = "Sets",
		["cBcael_Armor"]			= "Weapons & Armor",
		["cBcael_Quest"]			= "Quest Items",
		["cBcael_Consumables"]	= "Consumables",
        ["cBcael_TradeGoods"]	= "Trade Goods",
		["cBcael_Bag"]			= "Inventory",
		["cBcael_Keyring"]		= "Keyring",
		["cBcael_NewItems"]		= "New Items",
    }	
end